trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  acrServiceConnection: 'sc-acr'
  acrName: 'acrvotingapp7f7e43aa.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: 'Pruebas automatizadas'
  jobs:
  - job: RunTests
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
    - script: |
        cd src
        npm ci
        npm run start-bg
        sleep 5
        npm test
      displayName: 'Instalar, arrancar server, correr pruebas'

- stage: Build
  displayName: 'Construir y publicar imagen'
  dependsOn: Test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: BuildImage
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: 'nodejs-demoapp'
        command: 'buildAndPush'
        Dockerfile: 'build/Dockerfile'
        buildContext: '.'
        tags: |
          $(tag)
          latest

- stage: DeployStaging
  displayName: 'Desplegar en Staging'
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToStaging
    pool: { vmImage: 'ubuntu-latest' }
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'sc-azure-arm'
              azureResourceGroup: 'rg-devops-lab-tf'
              kubernetesCluster: 'aks-devops-lab-tf'
              namespace: 'nodejsdemo-staging'
              manifests: |
                k8s/staging.yaml
              containers: |
                $(acrName)/nodejs-demoapp:$(tag)

- stage: DeployCanary
  displayName: 'Desplegar Canary (20% trafico)'
  dependsOn: DeployStaging
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToCanary
    pool: { vmImage: 'ubuntu-latest' }
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            displayName: 'Deploy solo canary'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'sc-azure-arm'
              azureResourceGroup: 'rg-devops-lab-tf'
              kubernetesCluster: 'aks-devops-lab-tf'
              namespace: 'nodejsdemo-production'
              manifests: |
                k8s/production-canary.yaml
              containers: |
                $(acrName)/nodejs-demoapp:$(tag)

- stage: PromoteToStable
  displayName: 'Promover Canary a Estable (100% trafico)'
  dependsOn: DeployCanary
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: PromoteStable
    pool: { vmImage: 'ubuntu-latest' }
    environment: 'production-promote'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            displayName: 'Actualizar version estable'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'sc-azure-arm'
              azureResourceGroup: 'rg-devops-lab-tf'
              kubernetesCluster: 'aks-devops-lab-tf'
              namespace: 'nodejsdemo-production'
              manifests: |
                k8s/production-stable.yaml
              containers: |
                $(acrName)/nodejs-demoapp:$(tag)
